



services:
  app:
    image: tameer/firefly:0.0.23
    ports:
      - "8082:8080"

    env_file:
      - .aws-test.env

    volumes:
      - ./.aws-test.env:/var/www/html/.env:ro
      - firefly_storage:/var/www/html/storage 
    environment:
      # === בסיס אפליקציה ===
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: "http://3.248.215.96:8082/"
      APP_KEY: "base64:Oxn3bza9hwTes4by6ySdvRNCKoSWFHS9IN1s8Haaab4="

      # === DB ===
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: firefly
      DB_USERNAME: firefly
      DB_PASSWORD: firefly

      # === כיבוי 2FA שמפיל את ההורדה ===
      GOOGLE2FA_ENABLED: "false"
      GOOGLE2FA_MIDDLEWARE_ENABLED: "false"

      # === Receipt Inbox ===
      RECEIPT_INBOX_ENABLED: "true"
      FIREFLY_API_BASE: "http://127.0.0.1:8080"
      FIREFLY_PERSONAL_TOKEN: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzk3MzY5YzJkMjZkYTEzNDNjZGY5N2E5YWIwNzhkYmIxYmFhODQzNGNhZjRhZTBkMzFmNGQ2MzM5MjMxZDA3MWJhOGMzZDVmYWU2MDNkNDgiLCJpYXQiOjE3NTkyMjM2OTYuNjA3NjI4LCJuYmYiOjE3NTkyMjM2OTYuNjA3NjMsImV4cCI6MTc5MDc1OTY5Ni41NDQxNzcsInN1YiI6IjEiLCJzY29wZXMiOltdfQ.ZgXwEJcyV4y9YAYWkP6mObyLAB67RzAptknuO0UxT9Gnu96lfs37e5XVRTuaQGyspNvJhtaIx_lnKybGKqAu5vXzT6GM1hX1FphqBEJNTegOl7rcQubKqYtTCBMDcAz1UQsH_vI93C6pEbadL1ipMyH4_SsXbeTSDer3CggV-32ObAvBI2JXgKVBZozoMcYUWfXjTEKUxAX1POcSrnCcoKIMmXm2W8FPE5zACcnSsLgjI_DobETXFErosKzjqfR1tckPLoQSlaPqJY8xUSySCQmONQjxJCwcZOnRmh652FS0EiBELucaO0gKQtH6GmZVoWxefeKfdEDVRirW5ITS__LNHkqbxgGGivdSN0Qj321kYBialjVQmNs8mry8PS1V85Ul4Vap4dlr8J27m40hlX41stQeq_c8LFBv-GB3TLiA_WnYDSsnOVMaymL8ighGDFEv7GkJbydM-H-MiU_76tuGl013X2b7y5VdmZlAvX8MXhCFXK66gnd_32D-ubXmm8h_LJOx8mWoFKxNCMVoWHyBz0W-TWsSktH8xlfQPELbzt60VLZ05bWRqBbIjc6j2m-GXz60sNR9soVMZVi7rcQnhAvba5jOTDlPlGDD8Faqewqr1Xt5_7PBqgvDGfn08xOig0vgCP7NR4TuUCeMyNPvhLBbXWZl5Yhmb8d-SSw"
      # === Parser שרץ על ה-Host ===
      RECEIPT_PARSER_URL: "http://parser:8000"

    depends_on:
      - db
      - parser
    restart: unless-stopped

    parser:
      image: tameer/parser:0.0.2
      ports:
        - "8000:8000"
      env_file:
       - .aws-test.env
      healthcheck:
        test: ["CMD-SHELL", "python -c \"import socket,sys; s=socket.socket(); s.settimeout(2); s.connect(('127.0.0.1',8000)); s.close(); sys.exit(0)\""]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 10s
      restart: unless-stopped

    db:
      image: mariadb:10.11
      environment:
        MARIADB_DATABASE: firefly
        MARIADB_USER: firefly
        MARIADB_PASSWORD: firefly
        MARIADB_ROOT_PASSWORD: root
      volumes:
        - db_data:/var/lib/mysql
      restart: unless-stopped

  volumes:
    db_data:








# docker compose -f compose.ec2.yml logs -f app
# docker compose -f compose.ec2.yml logs -f parser



# ubuntu@ip-172-31-32-47:~/firefly$ docker compose -f compose.ec2.yml exec app sh -lc '
# printf "%s" "$FIREFLY_PERSONAL_TOKEN" | tail -c 12; printf "\n"
# '
# JoZTS-ANiVq8


  # volumes:
  #     - ./.env:/var/www/html/.env:ro

# services:
#   app:
#     image: tameer/firefly:0.0.23
#     ports:
#       - "8082:8080"

#     env_file:
#       - .aws-test.env

#     volumes:
#       - ./.env:/var/www/html/.env:ro 
#     environment:
#       # === בסיס אפליקציה ===
#       APP_ENV: production
#       APP_DEBUG: "false"
#       APP_URL: "http://108.129.168.117:8082/"
#       APP_KEY: "base64:Oxn3bza9hwTes4by6ySdvRNCKoSWFHS9IN1s8Haaab4="

#       # === DB ===
#       DB_CONNECTION: mysql
#       DB_HOST: db
#       DB_PORT: 3306
#       DB_DATABASE: firefly
#       DB_USERNAME: firefly
#       DB_PASSWORD: firefly

#       # === כיבוי 2FA שמפיל את ההורדה ===
#       GOOGLE2FA_ENABLED: "false"
#       GOOGLE2FA_MIDDLEWARE_ENABLED: "false"

#       # === Receipt Inbox ===
#       RECEIPT_INBOX_ENABLED: "true"
#       FIREFLY_API_BASE: "http://127.0.0.1:8080"
#       FIREFLY_PERSONAL_TOKEN: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZjcwNjg3ZjEyZmIyNmRkOWU4NGIxYTM3NDQwMjBkMjdjOGE4OGRjYzM1Y2UwYWZiNDI5ZjM1MWRmZDUyMWU3MWM3M2FlYjgyZGY1NGU2MDUiLCJpYXQiOjE3NTkwOTU1NTMuNDkwMTcsIm5iZiI6MTc1OTA5NTU1My40OTAxNzIsImV4cCI6MTc5MDYzMTU1My4xMzY2MzMsInN1YiI6IjEiLCJzY29wZXMiOltdfQ.haSeS3q-Z_73-HFgnsfis5EdhirgJKROrU9mzTbCEYvAfNlFoTypwCNjFAGLG2sroDrqDAbG0wr8giVLo7day0g073DhGUnWeE4LskgE2Ws0Mzu5HnVytiWdAmNKepwsgZaOQGDKJUlgarQ6qIOiVKAq4CmYU_vZajfqyQOisAjDm1o6oGodZ4-SP5l5otywSz2pmFXQ6T7fMOGGGX0wBYhQNjMhSYkCL-i12Zax_d4OyrlGNfjs_lybmcEatat_Mmg5eALVMFcORn8B1_G2j-QFxhmSr6tyUG3VxcQMLz7QyHntMWaaXcJ75jPqiDEXu4mBV6CLxEF3nxV5VhqyYKdeJpyh866j7P2kyo2B2cofYxN2KRu8sDbBUEOaGo0ox6IZBAUXCoV8Va4dF-bi5lZwXvU1MMIA3vh-H7Wly3eHUd_dZw4tIoisxQRdoV64_8WCQYvQAKmmt01WKnUXx0w5qdFtE-SSpd-OZENE_q6A3kYk-VwY63QG4gZouHaRO21WJ4W_FPwI_aP4B7btlCH5ZcBpfpfomFvy2FFx8jl_SfHYNJPARoPaSNhCcVW4l5LiJE6bLnQX4g6YXqU2cIOjgYG53bb8E-sqJ6NqXMMFi0_-S8f-mVHWwdRnmxzp8zu4Wv1TEbqoGQFRqR7iqH-m3pKHLscn0RJV7-ypdhA"

#       # === Parser שרץ על ה-Host ===
#       RECEIPT_PARSER_URL: "http://parser:8000"

#     depends_on:
#       - db
#       - parser
#     restart: unless-stopped

#     parser:
#       image: tameer/parser:0.0.1
#       ports:
#         - "8000:8000"
#       restart: unless-stopped

#     db:
#       image: mariadb:10.11
#       environment:
#         MARIADB_DATABASE: firefly
#         MARIADB_USER: firefly
#         MARIADB_PASSWORD: firefly
#         MARIADB_ROOT_PASSWORD: root
#       volumes:
#         - db_data:/var/lib/mysql
#       restart: unless-stopped

#   volumes:
#     db_data:







# docker compose -f compose.ec2.yml logs -f app
# docker compose -f compose.ec2.yml logs -f parser


      # === S3 ===
      # AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      # AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      # AWS_DEFAULT_REGION: "eu-west-1"
      # AWS_BUCKET: "tameerfirefly"
      # RECEIPT_S3_BUCKET: "tameerfirefly"   # ← תואם ל-AWS_BUCKET
      # RECEIPT_S3_DISK: "s3"
      # RECEIPT_S3_PREFIX: "receipts/"
      # RECEIPT_S3_SIGNED_URL_SECONDS: "900"

# services:
#   app:
#     image: firefly:0.0.14
#     ports:
#       - "8082:8080"
#     environment:
#       APP_ENV: local
#       APP_DEBUG: "true"
#       APP_URL: "http://localhost:8082"
#       APP_KEY: "base64:Oxn3bza9hwTes4by6ySdvRNCKoSWFHS9IN1s8Haaab4="
#       DB_CONNECTION: mysql
#       DB_HOST: db
#       DB_PORT: 3306
#       DB_DATABASE: firefly
#       DB_USERNAME: firefly
#       DB_PASSWORD: firefly

#       # Receipt Inbox
#       RECEIPT_INBOX_ENABLED: "true"
#       FIREFLY_API_BASE: "http://127.0.0.1:8080"
#       FIREFLY_PERSONAL_TOKEN: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMjc3Yjg2OTg1YzAxZGY2MDNiMDAzZDFhYThhMzg4MmE3MzhhZjEzZGM1MTI4YjUxNjRlNDM3NWQ3ZDk5YzZjODNkOWQ2YzlmNTFkMmY5NmEiLCJpYXQiOjE3NTg1Njc2NjEuMTU1OTAxLCJuYmYiOjE3NTg1Njc2NjEuMTU1OTAyLCJleHAiOjE3OTAxMDM2NjEuMTM1ODU2LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.YTs68_YqT23O-Su-Vzz88uEZ2A0Ogo5R3ddC4PRi0DVo1X44um0P7w40hbfOl1flJx_W61agowMA2JTsvtVx1HTnPhE3dg_X3kdW47r0kK3fmbGqles4_wla5xD5xwnJUDSWMEcAVrmkx4tbFJs39snVqCJ8EsVC4yVLVbpanCBk9nuTNvmgHJhPO8ZK_GcqfY-ZYpq2kKU-HIKh3Q7xSR2uZnldr1ihp65Qik-vExGflqVaV3l5vI8Gekc9bsQjApOzeusFYdUtK43XbL_b-JwPqGQSc0EORbC4gohRm3CrsAA-JCzc1dEQ3VJyah70V1P7D7wFzU4QfGynFJ1FGfWWwFKBo-bFNAQBqjlOu8QUR8Ahec2_RxpnNq39lsnazoFKETUT7zQwA7lWgl1px8twFyLCr9ww8SdyEABYiKfQGK-gwsJ5fYf76EIiSrJ8G-26WlwkJ6H42Q1gX7S_cKXTRsjZS0Kytty-tqHpFVFeFpJKP8yn71i2ughlTEWFdqoXSis2MamkEgt7JqHGzfLyZA2I49yG0Qhf0Zz5rWftGUxAZIlKbFMn4UMjpbYqFqPl2X0nxewLxEwwAoJWwhYyj61Bs2Tk2xeh-A3zCpBvdQdCjEkGLfxFPedlY2THMy5VKImZoQqHuZV-kZWoj2OoAkoUTkQKhzi34H278kk"

#       # parser שרץ על ה-Host
#       RECEIPT_PARSER_URL: "http://host.docker.internal:8000"

#       # --- S3 (כבר עבד אצלך) ---
#       AWS_ACCESS_KEY_ID: AKIATKJU5R37TGA7TQEY
#       AWS_SECRET_ACCESS_KEY: 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
#       AWS_DEFAULT_REGION: "eu-west-1"
#       AWS_BUCKET: "tameerfirefly"
#       RECEIPT_S3_DISK: "s3"
#       RECEIPT_S3_PREFIX: "receipts/"
#       RECEIPT_S3_SIGNED_URL_SECONDS: "900"

#     depends_on:
#       - db
#     restart: unless-stopped
#     extra_hosts:
#       - "host.docker.internal:host-gateway"

#   db:
#     image: mariadb:10.11
#     environment:
#       MARIADB_DATABASE: firefly
#       MARIADB_USER: firefly
#       MARIADB_PASSWORD: firefly
#       MARIADB_ROOT_PASSWORD: root
#     volumes:
#       - db_data:/var/lib/mysql
#     restart: unless-stopped

# volumes:
#   db_data:




# services:
#   app:
#     image: firefly:0.0.7
#     ports:
#       - "8082:8080"
#     environment:
#       APP_ENV: local
#       APP_DEBUG: "true"
#       APP_URL: "http://localhost:8082"
#       APP_KEY: "base64:Oxn3bza9hwTes4by6ySdvRNCKoSWFHS9IN1s8Haaab4="
#       DB_CONNECTION: mysql
#       DB_HOST: db
#       DB_PORT: 3306
#       DB_DATABASE: firefly
#       DB_USERNAME: firefly
#       DB_PASSWORD: firefly
#       # Receipt Inbox
#       RECEIPT_INBOX_ENABLED: "true"
#       FIREFLY_API_BASE: "http://127.0.0.1:8080"
#       FIREFLY_PERSONAL_TOKEN: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMjc3Yjg2OTg1YzAxZGY2MDNiMDAzZDFhYThhMzg4MmE3MzhhZjEzZGM1MTI4YjUxNjRlNDM3NWQ3ZDk5YzZjODNkOWQ2YzlmNTFkMmY5NmEiLCJpYXQiOjE3NTg1Njc2NjEuMTU1OTAxLCJuYmYiOjE3NTg1Njc2NjEuMTU1OTAyLCJleHAiOjE3OTAxMDM2NjEuMTM1ODU2LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.YTs68_YqT23O-Su-Vzz88uEZ2A0Ogo5R3ddC4PRi0DVo1X44um0P7w40hbfOl1flJx_W61agowMA2JTsvtVx1HTnPhE3dg_X3kdW47r0kK3fmbGqles4_wla5xD5xwnJUDSWMEcAVrmkx4tbFJs39snVqCJ8EsVC4yVLVbpanCBk9nuTNvmgHJhPO8ZK_GcqfY-ZYpq2kKU-HIKh3Q7xSR2uZnldr1ihp65Qik-vExGflqVaV3l5vI8Gekc9bsQjApOzeusFYdUtK43XbL_b-JwPqGQSc0EORbC4gohRm3CrsAA-JCzc1dEQ3VJyah70V1P7D7wFzU4QfGynFJ1FGfWWwFKBo-bFNAQBqjlOu8QUR8Ahec2_RxpnNq39lsnazoFKETUT7zQwA7lWgl1px8twFyLCr9ww8SdyEABYiKfQGK-gwsJ5fYf76EIiSrJ8G-26WlwkJ6H42Q1gX7S_cKXTRsjZS0Kytty-tqHpFVFeFpJKP8yn71i2ughlTEWFdqoXSis2MamkEgt7JqHGzfLyZA2I49yG0Qhf0Zz5rWftGUxAZIlKbFMn4UMjpbYqFqPl2X0nxewLxEwwAoJWwhYyj61Bs2Tk2xeh-A3zCpBvdQdCjEkGLfxFPedlY2THMy5VKImZoQqHuZV-kZWoj2OoAkoUTkQKhzi34H278kk"
#       # אם שירות ה-parser רץ על ה-Host (Mac/Windows עם Docker Desktop):
#       # מתוך הקונטיינר צריך לקרוא ל-host.docker.internal במקום localhost
#       RECEIPT_PARSER_URL: "http://host.docker.internal:8000"

#     depends_on:
#       - db
#     restart: unless-stopped

#     # מאפשר לקונטיינר להגיע ל-host.docker.internal גם בלינוקס חדשים
#     extra_hosts:
#       - "host.docker.internal:host-gateway"

#   db:
#     image: mariadb:10.11
#     environment:
#       MARIADB_DATABASE: firefly
#       MARIADB_USER: firefly
#       MARIADB_PASSWORD: firefly
#       MARIADB_ROOT_PASSWORD: root
#     volumes:
#       - db_data:/var/lib/mysql
#     restart: unless-stopped

# volumes:
#   db_data:






# services:
#   app:
#     image: firefly:0.0.5
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "8082:8080"
#     environment:
#       APP_ENV: local
#       APP_DEBUG: "true"
#       APP_URL: "http://localhost:8082"
#       APP_KEY: "base64:Oxn3bza9hwTes4by6ySdvRNCKoSWFHS9IN1s8Haaab4="
#       DB_CONNECTION: mysql
#       DB_HOST: db
#       DB_PORT: 3306
#       DB_DATABASE: firefly
#       DB_USERNAME: firefly
#       DB_PASSWORD: firefly
#       # Receipt Inbox
#       RECEIPT_INBOX_ENABLED: "true"
#       FIREFLY_API_BASE: "http://127.0.0.1:8080"
#       FIREFLY_PERSONAL_TOKEN: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMjc3Yjg2OTg1YzAxZGY2MDNiMDAzZDFhYThhMzg4MmE3MzhhZjEzZGM1MTI4YjUxNjRlNDM3NWQ3ZDk5YzZjODNkOWQ2YzlmNTFkMmY5NmEiLCJpYXQiOjE3NTg1Njc2NjEuMTU1OTAxLCJuYmYiOjE3NTg1Njc2NjEuMTU1OTAyLCJleHAiOjE3OTAxMDM2NjEuMTM1ODU2LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.YTs68_YqT23O-Su-Vzz88uEZ2A0Ogo5R3ddC4PRi0DVo1X44um0P7w40hbfOl1flJx_W61agowMA2JTsvtVx1HTnPhE3dg_X3kdW47r0kK3fmbGqles4_wla5xD5xwnJUDSWMEcAVrmkx4tbFJs39snVqCJ8EsVC4yVLVbpanCBk9nuTNvmgHJhPO8ZK_GcqfY-ZYpq2kKU-HIKh3Q7xSR2uZnldr1ihp65Qik-vExGflqVaV3l5vI8Gekc9bsQjApOzeusFYdUtK43XbL_b-JwPqGQSc0EORbC4gohRm3CrsAA-JCzc1dEQ3VJyah70V1P7D7wFzU4QfGynFJ1FGfWWwFKBo-bFNAQBqjlOu8QUR8Ahec2_RxpnNq39lsnazoFKETUT7zQwA7lWgl1px8twFyLCr9ww8SdyEABYiKfQGK-gwsJ5fYf76EIiSrJ8G-26WlwkJ6H42Q1gX7S_cKXTRsjZS0Kytty-tqHpFVFeFpJKP8yn71i2ughlTEWFdqoXSis2MamkEgt7JqHGzfLyZA2I49yG0Qhf0Zz5rWftGUxAZIlKbFMn4UMjpbYqFqPl2X0nxewLxEwwAoJWwhYyj61Bs2Tk2xeh-A3zCpBvdQdCjEkGLfxFPedlY2THMy5VKImZoQqHuZV-kZWoj2OoAkoUTkQKhzi34H278kk"
#       # אם שירות ה-parser רץ על ה-Host (Mac/Windows עם Docker Desktop):
#       # מתוך הקונטיינר צריך לקרוא ל-host.docker.internal במקום localhost
#       RECEIPT_PARSER_URL: "http://host.docker.internal:8000"

#     depends_on:
#       - db
#     restart: unless-stopped

#     # מאפשר לקונטיינר להגיע ל-host.docker.internal גם בלינוקס חדשים
#     extra_hosts:
#       - "host.docker.internal:host-gateway"

#   db:
#     image: mariadb:10.11
#     environment:
#       MARIADB_DATABASE: firefly
#       MARIADB_USER: firefly
#       MARIADB_PASSWORD: firefly
#       MARIADB_ROOT_PASSWORD: root
#     volumes:
#       - db_data:/var/lib/mysql
#     restart: unless-stopped

# volumes:
#   db_data:




# docker compose build app --no-cache
# docker compose up -d --force-recreate